# data set on which to train, available options:
# path to json contains jet events
# mnist: uses the MNIST data set for testing
data: ../data/valid/valid_QCD_500GeV.json.gz

# Number of events
nev: -1 # -1 = all data

# Select model, available options are:
# gan, dcgan, wgan, wgangp, vae, aae, bgan, lsgan
model: aae

# Number of epochs
epochs: 100

# Batch size
batch_size: 32

# Number of generated events
ngen: 5000

# Number of latent dimensions
latdim: 100

# Number of pixels
npx: 24

# scaler for preprocessing
scaler: minmax

# Perform PCA preprocessing
pca: true
pca_fraction: 0.95

# Perform ZCA preprocessing
zca: false

# Number of pixel average
navg: 20

# Optimizer parameters
# options are: Adam, RMSprop, Adagrad, SGD
optimizer: Adam
learning_rate: 0.0002
opt_beta1: 0.5

# AAE architecture parameters
nn_units_discr: 256
nn_units_enc: 256
nn_units_dec: 256
nn_alpha_discr: 0.2
nn_alpha_enc: 0.2
nn_alpha_dec: 0.2
