# data set on which to train, available options:
# path to json contains jet events
# mnist: uses the MNIST data set for testing
data: ../data/valid/valid_QCD_500GeV.json.gz

# Number of events
nev: -1 # -1 = all data

# Select model, available options are:
# gan, dcgan, wgan, wgangp, vae, aae, bgan, lsgan
model: wgan

# Number of epochs
epochs: 40

# Batch size
batch_size: 32

# Number of generated events
ngen: 5000

# Number of latent dimensions
latdim: 100

# Number of pixels
npx: 20

# Perform PCA preprocessing
pca: false

# Perform ZCA preprocessing
zca: true

# Number of pixel average
navg: 4
deterministic: false

# Optimizer parameters
# options are: Adam, RMSprop, Adagrad, SGD
optimizer: RMSprop
learning_rate: 0.00005

# WGAN architecture parameters
n_critic: 5
clip_value: 0.01
nn_smallest_unit: 16
nn_alpha: 0.2
nn_momentum: 0.8
nn_dropout: 0.25
